import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const entriesDir = join(__dirname, '..', 'src', 'faq', 'entries');
const outputFile = join(__dirname, '..', 'src', 'faq', 'faq-entries.generated.ts');

const files = readdirSync(entriesDir).filter((f) => f.endsWith('.md')).sort();

// Heading format: # <title>  (any heading level, no id prefix needed - id comes from filename)
// File naming convention: 4-digit number AABB.md where AA = major topic, BB = sub-topic
// e.g. 0100.md, 0501.md  →  identifiers 100, 501
const HEADING_RE = /^#{1,6}\s+(.+)/;

const entries: Array<{ id: number; title: string; content: string }> = [];

for (const file of files) {
  const id = parseInt(basename(file, '.md'), 10);
  if (isNaN(id)) {
    console.warn(`Skipping ${file}: filename is not a valid number`);
    continue;
  }
  const raw = readFileSync(join(entriesDir, file), 'utf-8').trim();
  const match = raw.match(HEADING_RE);
  if (!match) {
    console.warn(`Skipping ${file}: no heading found`);
    continue;
  }
  const [, title] = match;
  const content = raw.split('\n').slice(1).join('\n').trim();
  const trimmedTitle = title.trim();
  if (trimmedTitle.length > 94) {
    console.warn(`The title of entry #${id} is too long, it will likely be trimmed in autocomplete results`);
  }
  entries.push({ id, title: trimmedTitle, content });
}

entries.sort((a, b) => a.id - b.id);

const entriesBlock = entries
  .map((entry) => `  ${entry.id}: ${JSON.stringify(entry, null, 4)},`)
  .join('\n');

const output = `// This file is auto-generated by utils/generate-faq.ts - do not edit manually.
// Add or edit .md files in src/faq/entries/ and run \`npm run generate-faq\` to update.
// File naming: AABB.md where AA = major topic (00–99), BB = sub-topic (00–99)

export interface FaqEntry {
  id: number;
  title: string;
  content: string;
}

const _FAQ_ENTRIES = {
${entriesBlock}
} as const satisfies Record<number, FaqEntry>;

export type FaqEntryKey = keyof typeof _FAQ_ENTRIES;

// Typed as Record so it remains indexable even when the entries object is empty.
export const FAQ_ENTRIES: Record<number, FaqEntry> = _FAQ_ENTRIES;
`;

writeFileSync(outputFile, output, 'utf-8');
console.log(`Generated ${outputFile} with ${entries.length} FAQ entr${entries.length === 1 ? 'y' : 'ies'}`);
