name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DISCORD_BOT_TOKEN: MOCK_DISCORD_BOT_TOKEN
  DISCORD_CLIENT_ID: MOCK_DISCORD_CLIENT_ID
  UA_STRING: MOCK_UA_STRING
  DISCORD_INVITE_URL: MOCK_DISCORD_INVITE_URL
  API_URL: MOCK_API_URL
  API_TOKEN: MOCK_API_TOKEN

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: 'Building, Linting and Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup pnpm
        uses: pnpm/action-setup@d15e628ca66d93ee5f352c71671a7bc6a97af5c9 # v6.0.8

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - run: pnpm run lint

      - run: pnpm run test

      - run: pnpm run build
