name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DISCORD_BOT_TOKEN: MOCK_DISCORD_BOT_TOKEN
  DISCORD_CLIENT_ID: MOCK_DISCORD_CLIENT_ID
  UA_STRING: MOCK_UA_STRING
  DISCORD_INVITE_URL: MOCK_DISCORD_INVITE_URL
  API_URL: MOCK_API_URL
  API_TOKEN: MOCK_API_TOKEN

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: 'Building, Linting and Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install npm dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - run: npm run lint

      - run: npm run test

      - run: npm run build
